### ISSUE TITLE
messageHubCredentialsFile should use toolkitDir instead of application directory for relative path

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.messagehub#54]
Message Hub credentials not found in properties file nor in an Application Configuration

at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:275)
at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator.initialize(AbstractKafkaConsumerOperator.java:475)
at com.ibm.streamsx.kafka.operators.AbstractKafkaOperator.initialize(AbstractKafkaOperator.java:98)
at com.ibm.streamsx.messagehub.operators.MessageHubConsumerOperator.loadProperties(MessageHubConsumerOperator.java:85)
at com.ibm.streamsx.kafka.operators.AbstractKafkaOperator.loadProperties(AbstractKafkaOperator.java:133)
at com.ibm.streamsx.messagehub.operators.MessageHubConsumerOperator.loadFromAppConfig(MessageHubConsumerOperator.java:96)
Exception in thread "Thread-11" java.lang.RuntimeException: Message Hub credentials not found in properties file nor in an Application Configuration

**Comment by markheger** [comment]
workaround:
param
                messageHubCredentialsFile : getThisToolkitDir()+"/etc/dedicatedMH.conf";

**Comment by markheger** [comment]
No, it is not the toolkit directory of the messageHub toolkit meant.
The toolkit directory of the composite using the toolkit operators and toolkit's etc dir providing some configuration files.
When using a toolkit (e.g. Test composite in SPL and etc dir) with TopologyTester the toolkitDirectory needs to used as prefix for parameters when relativ path is applied.

**Comment by RolefH** [comment]
I could not find a Java API similar to the SPL function ` spl.utility::getThisToolkitDir()` returns the toolkit directory of the Toolkit that contains the current SPL-File. That's why the workaround in SPL is doing what is expected. The description of the Java-API `OperatorContext.getToolkitDirectory()` looks cryptic to me:
```
java.io.File getToolkitDirectory()

Get the root directory of the toolkit that declares the getKind() of this operator invocation.
At SPL compile time this is the location of the toolkit specified to the SPL compiler sc.
At runtime this is the location of the toolkit in the application landing zone that has been unpacked from the application's bundle (sab file).

Returns:
    the absolute path of the toolkit root directory
Since: 
    InfoSphere® Streams Version 4.0 
```
https://www.ibm.com/support/knowledgecenter/SSCRJU_4.3.0/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/operator/OperatorContext.html#getToolkitDirectory--

For me it looks like it is returning the toolkit directory of the toolkit, that _invokes_ the operator, for example, the toolkit directory that contains the Main composite. But, what is returned when I write an SPL-toolkit X that wraps the Java operator and use this toolkit X in my applications, which belong to toolkit Y. Will the toolkit directory of X or Y be returned by the Java-API? If toolkit dir of X will be returned, the user would have to place the file in etc of toolkit X instead of Y. This is not the desired function as toolkit X may be as 'read-only' as the MH toolkit.

**Comment by ddebrunner** [comment]
It's returning the toolkit that declares the operator, not the operator invocation. So for a MH operator it would return the message hub toolkit.

**Comment by RolefH** [comment]
The solution will be an SPL doc update:

**messageHubCredentialsFile**
Specifies the name of the file that contains the complete Message Hub credentials JSON. If not specified, this parameter will attempt to load the credentials from the file etc/messagehub.json. A relative path is always interpreted as relative to the application directory of the Streams application. If the credential file is placed in the etc directory of the application bundle, specify `getThisToolkitDir() + "/etc/<your filename>"` as the parameter value.

**Comment by ddebrunner** [comment]
@RolefH That's a confusing doc update.

Files are not placed in the "etc directory of the application *bundle*", they can be placed in the etc directory of the application toolkit/directory. And then would be accessed using `etc/<your filename>`, no need for `getThisToolkitDir() `

I can't really see a need to ever use `getThisToolkitDir() ` for a credentials file. It means the file is hardcoded to a toolkit.

Typically its used when a toolkit needs to use a fixed resource from its own toolkit.

**Comment by RolefH** [comment]
Ok. Going to remove the last sentence:
```
    @Parameter(optional = true, name="messageHubCredentialsFile", description="Specifies the name of the file that contains "
    		+ "the complete Message Hub credentials JSON. If not specified, this parameter will "
    		+ "attempt to load the credentials from the file `etc/messagehub.json`. A relative path is always "
            + "interpreted as relative to the *application directory* of the Streams application.")
```
